# 时钟信号：100MHz，引脚 W5（xc7a35tcpg236-1 专用时钟引脚）
set_property PACKAGE_PIN W5 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} [get_ports sys_clk]

# 16位拨码开关 switch_in[15:0] - 批量优化约束，避免逐位冗余
set_property PACKAGE_PIN V17 [get_ports {switch_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {switch_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {switch_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {switch_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {switch_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {switch_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {switch_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {switch_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {switch_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {switch_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {switch_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {switch_in[15]}]
# 批量设置IO标准和上拉，简化写法
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[15:0]}]
set_property PULLTYPE PULLUP [get_ports {switch_in[15:0]}]

# 16位LED led_out[15:0] - 批量优化
set_property PACKAGE_PIN U16 [get_ports {led_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[15:0]}]

# 4位数码管 seg_out[7:0] + dig_out[3:0] - 批量优化
set_property PACKAGE_PIN W7 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7:0]}]

set_property PACKAGE_PIN U2 [get_ports {dig_out[0]}]
set_property PACKAGE_PIN U4 [get_ports {dig_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {dig_out[2]}]
set_property PACKAGE_PIN W4 [get_ports {dig_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[3:0]}]

# 5个按键 key_in[4:0]（修正引脚分配，避免混乱）
# key_in[0]=btnC(T18)、key_in[1]=btnU(W19)、key_in[2]=btnL(T17)、key_in[3]=btnR(U17)、key_in[4]=btnD(A14)
set_property PACKAGE_PIN T18 [get_ports {key_in[0]}]
set_property PACKAGE_PIN W19 [get_ports {key_in[1]}]
set_property PACKAGE_PIN T17 [get_ports {key_in[2]}]
set_property PACKAGE_PIN U17 [get_ports {key_in[3]}]
set_property PACKAGE_PIN A14 [get_ports {key_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[4:0]}]
set_property PULLTYPE PULLUP [get_ports {key_in[4:0]}]

# 复位按键 rst（复用 btnC，引脚 U18，无引脚冲突）
# set_property PACKAGE_PIN U18 [get_ports rst]
# set_property IOSTANDARD LVCMOS33 [get_ports rst]
# set_property PULLTYPE PULLUP [get_ports rst]

# ========== 核心修复：彻底禁用switch_in[15]的时钟路由 ==========
# 1. 精准匹配错误提示的网表名
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {switch_in_IBUF[15]}]
# 2. 兜底：禁用整个switch_in总线的时钟路由（防止工具误判）
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {switch_in[15:0]}]
# 3. 强制标记switch_in[15]为普通IO，排除时钟属性
set_property CLOCK_GROUP -asynchronous [get_clocks -of_objects [get_nets switch_in_IBUF[15]]]

set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[0]}]
