## Basys3 官方约束 - 适配 xc7a35tcpg236-1 芯片 + OpenMIPS 工程

## 时钟信号（100MHz，引脚 W5）
set_property PACKAGE_PIN W5 [get_ports sys_clk]							
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports sys_clk]
 
## 16位拨码开关（switch_in[15:0]）
set_property PACKAGE_PIN V17 [get_ports {switch_in[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch_in[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch_in[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch_in[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch_in[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {switch_in[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {switch_in[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {switch_in[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {switch_in[8]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {switch_in[9]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {switch_in[10]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {switch_in[11]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {switch_in[12]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {switch_in[13]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {switch_in[14]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {switch_in[15]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {switch_in[15]}]
set_property PULLUP TRUE [get_ports switch_in]
## 【关键修改2：规范PULLUP约束，指定所有switch_in位】
set_property PULLUP TRUE [get_ports {switch_in[15:0]}]

## 16位LED（led_out[15:0]）
set_property PACKAGE_PIN U16 [get_ports {led_out[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_out[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_out[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_out[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_out[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_out[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_out[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_out[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_out[8]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_out[9]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_out[10]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_out[11]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_out[12]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_out[13]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_out[14]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_out[15]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[15]}]

## 4位8段数码管（seg_out[7:0]/dig_out[3:0]）
set_property PACKAGE_PIN W7 [get_ports {seg_out[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_out[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_out[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_out[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_out[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_out[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_out[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg_out[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]

set_property PACKAGE_PIN U2 [get_ports {dig_out[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[0]}]
set_property PACKAGE_PIN U4 [get_ports {dig_out[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {dig_out[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[2]}]
set_property PACKAGE_PIN W4 [get_ports {dig_out[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {dig_out[3]}]

## 5个按键（key_in[4:0]，key_in[0]=btnC 中, 1=btnU 上, 2=btnL 左, 3=btnR 右, 4=btnD 下）
set_property PACKAGE_PIN U18 [get_ports {key_in[0]}]						
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]
set_property PACKAGE_PIN T18 [get_ports {key_in[1]}]						
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property PACKAGE_PIN W19 [get_ports {key_in[2]}]						
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]
set_property PACKAGE_PIN T17 [get_ports {key_in[3]}]						
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]
set_property PACKAGE_PIN U17 [get_ports {key_in[4]}]						
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[4]}]
set_property PULLUP TRUE [get_ports key_in]

# 强制禁止switch_in[15]走专用时钟路由（仅作最后兜底）
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets switch_in[15]]